

version: '3.4'
services:
  wscore:
    image: wscore
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - /opt/Programas/WS-Core:/opt/Programas/WS-Core
    hostname: wscore
  wssql:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'TTO@ws2021' # TODO: Change this
    volumes:
      - /opt/Database/WSCore:/var/lib/mysql
    hostname: wssql
    ports:
      - 3361:3306